const questions=[
 {n:1,t:'Spot the problems',q:'How many problems are visible in this picture? Assume the climber is climbing from the left.',o:['1','2','3','There are no problems'],a:'2',i:'images/question-1-problems.png',alt:'Indoor climber and rope system on a climbing wall'},
 {n:3,t:'Rock contact',q:'The lower carabiner is resting on a rock edge. What is the better choice?',o:['Leave it as it is','Use a longer quickdraw','Clip the rope higher','Twist the rope'],a:'Use a longer quickdraw',i:'images/question-5.png',alt:'Quickdraw positioned on a rock face'},
 {n:4,t:'Inspection',q:'This quickdraw is worn and hanging on the wall. Would you climb above it?',o:['Yes','No'],a:'No',i:'images/worn-quickdraw.png',alt:'Worn quickdraw hanging from a bolt on a rock wall'},
 {n:5,t:'Gear knowledge',q:'How can you usually identify the rope-side carabiner?',o:['It often has a STRING keeper and/or a bent gate','It is always the upper carabiner','It is always the larger carabiner','There is no difference'],a:'It often has a STRING keeper and/or a bent gate',i:'images/question-5-carabiner.png',alt:'Climbing carabiner and sling on a white background'},
 {n:6,t:'Positioning',q:'A climber is clipping very high while unstable. What is the main drawback?',o:['Nothing; high clipping is always better','It may require pulling extra rope and increase fall potential','It makes the bolt stronger','It automatically reduces rope drag'],a:'It may require pulling extra rope and increase fall potential',i:'images/question-6.png',alt:'Climber reaching high to clip a quickdraw'},
 {n:7,t:'Rope path',q:'What is the problem in this picture?',o:['Nothing is wrong','Back-clipping','Z-clipping','The quickdraw is too short'],a:'Back-clipping',i:'images/question-7.png',alt:'Climbing rope clipped incorrectly through a quickdraw'},
 {n:8,t:'Rope path',q:'Why can back-clipping be dangerous?',o:['The rope may run over the gate and open it in a fall','The bolt may unscrew','The sling becomes too long','The belayer automatically loses control'],a:'The rope may run over the gate and open it in a fall',i:'images/question-8.png',alt:'Climber beside a quickdraw and rope on a rock wall'},
 {n:9,t:'Rope management',q:'What usually creates a Z-clip?',o:['Taking rope from below the previous quickdraw','Clipping too low','Using a wiregate','Using a long sling'],a:'Taking rope from below the previous quickdraw',i:'images/question-9-zclip.png',alt:'Indoor climber demonstrating a rope path between quickdraws'},
 {n:10,t:'Back-clipping',q:'Why is back-clipping dangerous?',o:['In a fall, the rope can open the gate and clip out of the carabiner','It makes the quickdraw too short','It damages the bolt immediately','It always causes a Z-clip'],a:'In a fall, the rope can open the gate and clip out of the carabiner',i:'images/question-7.png',alt:'Climbing rope clipped incorrectly through a quickdraw'}
];
const app=document.querySelector('#app');let state={started:false,contact:{name:'',email:'',phone:''},at:0,answers:Array(questions.length).fill(''),selected:'',submitted:false,interest:''};
function brand(){return `<div class="brand"><img src="../pics/עין.png" alt="Climbing Cyprus logo"><div>Climbing Cyprus<small>Climbing, guiding and safety in Cyprus</small></div></div>`}
function render(){if(!state.started)return start();if(state.at>=questions.length)return result();let x=questions[state.at];app.innerHTML=`<div class="quiz-wrap">${brand()}<div class="quiz-top"><span>Question ${state.at+1} of ${questions.length}</span><span>With instructor Yonatan Cohen</span></div><div class="progress"><i style="width:${((state.at+(state.submitted?1:0))/questions.length)*100}%"></i></div><section class="quiz-card"><div class="photo"><img src="${x.i}" alt="${x.alt}"></div><div class="question-body"><div class="meta"><span>Question ${x.n} · ${x.t}</span><span>1 point</span></div><h1>${x.q}</h1><div class="options">${x.o.map((o,i)=>`<button class="option ${state.selected===o?'selected':''}" data-option="${encodeURIComponent(o)}" ${state.submitted?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${o}</span></button>`).join('')}</div><div class="footer"><button class="btn secondary" id="back" ${state.at===0?'disabled':''}>← Back</button>${state.submitted?`<button class="btn primary" id="next">${state.at===questions.length-1?'See my score':'Next question'} →</button>`:`<button class="btn primary" id="submit" ${state.selected?'':'disabled'}>Submit answer ↗</button>`}</div></div></section></div>`;bindQuiz()}
function start(){app.innerHTML=`<div class="quiz-wrap">${brand()}<section class="panel"><p class="eyebrow">Quickdraw & clipping safety</p><h1>Climbing safety quiz</h1><p class="intro">A short practical quiz with instructor Yonatan Cohen.</p><form class="form" id="startForm"><label>Full name<input name="name" required autocomplete="name"></label><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Phone<input name="phone" type="tel" required autocomplete="tel"></label><button class="btn primary">Start quiz →</button></form><p class="note">Your details are used to identify your result and any follow-up request you choose at the end.</p></section></div>`;document.querySelector('#startForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);state.contact=Object.fromEntries(f);state.started=true;render()}}
function bindQuiz(){document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{state.selected=decodeURIComponent(b.dataset.option);render()});document.querySelector('#back').onclick=()=>{if(state.at){state.at--;state.selected=state.answers[state.at];state.submitted=false;render()}};let submit=document.querySelector('#submit');if(submit)submit.onclick=()=>{if(state.selected){state.answers[state.at]=state.selected;state.submitted=true;render()}};let next=document.querySelector('#next');if(next)next.onclick=()=>{state.at++;state.selected=state.answers[state.at]||'';state.submitted=false;render()}}
function result(){let score=state.answers.reduce((s,a,i)=>s+(a===questions[i].a?1:0),0);app.innerHTML=`<div class="quiz-wrap result">${brand()}<section class="panel"><div class="result-head"><p class="instructor">With instructor Yonatan Cohen</p><div class="score"><strong>${score}</strong><span>/ ${questions.length}</span></div><h1>Quiz complete.</h1><p class="intro">${score>=8?'Strong safety instincts.':score>=6?'Good foundation — review the misses.':'Review the fundamentals before your next route.'}</p></div><div class="interest"><h2>Would you like Yonatan to contact you?</h2><p>Select what you are interested in:</p><select id="interest"><option value="">No follow-up requested</option><option>Guided climbing session in Cyprus</option><option>Climbing course in Cyprus</option><option>More information about climbing in Cyprus</option></select><a class="contact-link" id="contactLink" href="../index.html#contact" style="display:none">Request contact from Yonatan →</a></div><h2>Answer review</h2><div class="review">${questions.map((x,i)=>{let ok=state.answers[i]===x.a;return `<div class="review-item ${ok?'ok':''}"><div class="review-top"><b>Question ${x.n}</b><b>${ok?'Correct':'Incorrect'}</b></div><p>${x.q}</p><div class="review-answers"><span>Your answer: <b>${state.answers[i]||'No answer'}</b></span>${ok?'':`<span>Correct answer: <b>${x.a}</b></span>`}</div></div>`}).join('')}</div><div class="center"><button class="btn primary" id="again">Try again ↻</button></div><p class="note">A quiz is a learning tool, not a replacement for hands-on instruction and equipment checks.</p></section></div>`;document.querySelector('#interest').onchange=e=>{state.interest=e.target.value;let link=document.querySelector('#contactLink');link.style.display=e.target.value?'inline-block':'none';if(e.target.value)sessionStorage.setItem('climbingQuizLead',JSON.stringify({...state.contact,score,interest:e.target.value}))};document.querySelector('#again').onclick=()=>{state={...state,started:false,at:0,answers:Array(questions.length).fill(''),selected:'',submitted:false,interest:''};render()}}
render();
